services:
  youtarr:
    image: dialmaster/youtarr:latest
    container_name: youtarr
    restart: unless-stopped
    environment:
      IN_DOCKER_CONTAINER: 1
      DB_HOST: ${DB_HOST:?Set DB_HOST in config/external-db.env}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:?Set DB_USER in config/external-db.env}
      DB_PASSWORD: ${DB_PASSWORD:?Set DB_PASSWORD in config/external-db.env}
      DB_NAME: ${DB_NAME:-youtarr}
      AUTH_ENABLED: ${AUTH_ENABLED:-}
      AUTH_PRESET_USERNAME: ${AUTH_PRESET_USERNAME:-}
      AUTH_PRESET_PASSWORD: ${AUTH_PRESET_PASSWORD:-}
      LOG_LEVEL: ${LOG_LEVEL:-warn}
      START_MARIADB: "false"
      # Optional: Override config.json values via environment variables
      PLEX_IP: ${PLEX_IP:-}
      PLEX_PORT: ${PLEX_PORT:-}
      PLEX_API_KEY: ${PLEX_API_KEY:-}
      PLEX_LIBRARY_ID: ${PLEX_LIBRARY_ID:-}
      CHANNEL_AUTO_DOWNLOAD: ${CHANNEL_AUTO_DOWNLOAD:-}
      CHANNEL_FILES_TO_DOWNLOAD: ${CHANNEL_FILES_TO_DOWNLOAD:-}
      PREFERRED_RESOLUTION: ${PREFERRED_RESOLUTION:-}
      VIDEO_CODEC: ${VIDEO_CODEC:-}
      NOTIFICATIONS_ENABLED: ${NOTIFICATIONS_ENABLED:-}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3087:3011"
    volumes:
      # YOUTUBE_OUTPUT_DIR defaults to ./youtube-downloads if not set
      - ${YOUTUBE_OUTPUT_DIR:-./youtube-downloads}:/usr/src/app/data
      - ./server/images:/app/server/images
      - ./config:/app/config
      - ./jobs:/app/jobs
      - ./migrations:/app/migrations
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--show-error", "--output", "/dev/null", "http://localhost:3011/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: youtarr-network
